#!/bin/sh
#./vanet -a 5 -b 4 -s 1 -z 2 -c 2 -d 1 -f 2 -e 1 -m 2 -k 2 -g 1 -o 1 -h 1 -q 1 -m 2 -p ./param-configuration/param.conf -x ./output/output#1#2#1.txt -y ./output/output#1#2#1.xls
./vanet -d 2 -z 2 -a 5 -b 4 -s 1 -c 2 -f 2 -e 1 -m 2 -k 2 -g 1 -o 1 -h 1 -q 1 -m 2 -p ./param-configuration/param.conf -x ./output/output#1#2#1.txt -y ./output/output#1#2#1.xls